### PR TITLE
Add jeromekelleher and petrelharp as maintainers.

### PR DESCRIPTION
**Pull request by jeromekelleher**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by winni2k** [comment]
LGTM

**Review by winni2k — APPROVED** [review]

**Comment by jeromekelleher** [comment]
We should probably wait for @petrelharp to agree to being a maintainer before merging.

**Comment by petrelharp** [comment]
Yes!!! =)

**Comment by petrelharp** [comment]
And, thanks so much for doing this.

**Comment by winni2k** [comment]
You're welcome! Glad I could contribute.

**Pull request merged**
