### PR TITLE
update to 1.0.3

### PR DESCRIPTION
**Pull request by petrelharp**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by petrelharp** [comment]
@conda-forge-admin, please rerender

**Comment by petrelharp** [comment]
Could you have a look at this, @alxsimon? (I can't request you as a reviewer for some reason.)

**Comment by petrelharp** [comment]
@conda-forge-admin, please rerender

**Comment by alxsimon** [comment]
yes, that's good to go

**Pull request merged**
