### PR TITLE
update to v1.0.2

### PR DESCRIPTION
**Pull request by alxsimon**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by alxsimon** [comment]
@conda-forge-admin, please rerender

**Review by petrelharp — APPROVED** [review]
LGTM, thanks!

**Comment by petrelharp** [comment]
Thanks a bunch!! And hm, I thought this would happen automatically; do you know why it hasn't?

**Comment by alxsimon** [comment]
no idea why or how it's supposed to be set up sorry. I'm just dependent on conda for my current setup so thought I would ease the work.
Just seen your post on ecoevo, I'm happy to do the same for v1.0.3.

**Comment by petrelharp** [comment]
I've already got it going: https://github.com/conda-forge/pyslim-feedstock/pull/11 - thanks, though!

**Pull request merged**
